### ISSUE TITLE
Make a translucent info box appear on site load

### ISSUE THREAD

**Issue by abhinavk96** [CosmicCoder96/longDrive#3]
When the site loads a translucent pop over should appear which tells the user how to navigate the car by scrolling car horizontally.
Example:
![image](https://user-images.githubusercontent.com/17252805/35181843-948bc886-fdef-11e7-9e49-3e5107befce0.png)

**Comment by aadixiiita** [comment]
I would like to work on this

**Comment by ekanban** [comment]
I'd like to try this

**Comment by abhinavk96** [comment]
@aadixiiita please go ahead.
